title: Leaf Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf
permalink: ':slug'
social:
  twitter: _SupunKavinda
  github: SupunKavinda
plugins:
  - jekyll-feed
  - jekyll-seo-tag
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
baseurl: ''
url: ''
